# Run with: sudo docker-compose -f docker-compose.yml up
version: '3'
networks:
  redis:
  
services:
  redis:
    image: redis
    command: redis-server --requirepass $REDIS_PASSWORD
    restart: always
    networks:
      - redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - redis
    depends_on:
      - redis
  portr:
    build:
      context: .
      dockerfile: Dockerfile.portr
    environment:
      - PORTR_KEY=${PORTR_KEY}
      - GATEWAY_DOMAIN=${GATEWAY_DOMAIN}
    depends_on:
      - redis
    networks:
      - redis
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.portr
  #   command: pytest tests/test_redis_gateway.py -v
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   depends_on:
  #     - redis
  #   networks:
  #     - redis
#   visualizer:
#     image: bla
  #   depends_on:
  #     - redis
    