FROM ubuntu:22.04

RUN apt-get update && apt-get install -y wget unzip

WORKDIR /app

RUN wget https://github.com/amalshaji/portr/releases/download/0.0.27-beta/portr_0.0.27-beta_Linux_x86_64.zip && \
    unzip portr_0.0.27-beta_Linux_x86_64.zip && \
    rm portr_0.0.27-beta_Linux_x86_64.zip

COPY start_tunnel.sh .
RUN chmod +x start_tunnel.sh

CMD ["./start_tunnel.sh"]
